### ISSUE TITLE
Making repository a template

### ISSUE THREAD

**Issue by bonkboykz** [Saluki/nestjs-template#11]
Hello! Thanks for the neat template!

How about making this repository a template? [It's just a checkbox in the settings](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository)

**Comment by Saluki** [comment]
Hello @bonkboykz :wave: 

Thank you for the suggestion, I never used this Github feature before... but it is indeed perfect for this repository.
The nestjs-template project is now a template repository.
