### ISSUE TITLE
Questions about Guard and configProvider

### ISSUE THREAD

**Issue by ahmadichsan** [Saluki/nestjs-template#14]
Hello, first of all I'd like to say thanks to you for creating this complete nestjs template. It's helps a lot for me who just start jump into nestjs. I've several questions:

1. What is the ```GuestGuard``` and ```RestrictedGuard``` class used for and how to use/implement it?
2. There is a ```configProvider``` constants which has several field and imported in ```CommonModule```.
     a. is there any documentation where I could understand more about this ```configProvider```? What are the possible value for ```provide``` field? Is there any other fields besides ```provide``` and ```useFactory```?
     b. How this ```configProvider``` works, since its just being imported as ```providers``` in ```CommonModule``` and I did not found any where else where this ```configProvider``` being used again?

Thank you in advance.

**Comment by Saluki** [comment]
Hello @ahmdichsan,

The `GuestGuard` and `RestrictedGuard` are basic authentication mechanisms that can be used with the NestJS `@UseGuards` syntax. By using a `@UseGuards(RestrictedGuard)` on a controller or method, the request will only be allowed if the user sends a JWT token (that has been signed with the `JWT_SECRET` environment variable and the HS256 algorithm). See the [dedicated NestJS documentation](https://docs.nestjs.com/guards#binding-guards) and the `security-utils.ts` file for more details. 

The goal of the `configProvider` is to make a standard configuration available in the whole application. It uses the NestJS custom provider approach to make an object available in all controllers/services (I highly [recommend this documentation for more details on the subject](https://docs.nestjs.com/fundamentals/custom-providers#custom-providers-1)). Use the `@Inject(Service.CONFIG) config: Config` in your controllers and services :+1: 

Please take a look at the latest changes in `passenger.controller.ts` and `passenger.spec.ts` for usage examples.

**Comment by ahmadichsan** [comment]
Thanks @Saluki for the explanation and update on the repo!

I'd like to ask again about the ```@UseGuards(RestrictedGuard)```, does it means the default of a route/API endpoint is not restricted? Cause I'm sure there will be much more restricted route than the non-restricted route. Do I have to put ```@UseGuards(RestrictedGuard)``` everywhere? Is it anyway I could just set it once for all and if I have exception for several routes which not restricted, I could just add some config maybe to make it excluded from the global config?

**Comment by Saluki** [comment]
Hi @ahmdichsan,

This highly depends on the API use-case. You could use the `@UseGuards(RestrictedGuard)` on each controller or on specific routes (the `UseGuards` annotation can be used on the controller level).

**Comment by ahmadichsan** [comment]
thanks a lot @Saluki !
