### ISSUE TITLE
docs: using JWT

### ISSUE THREAD

**Issue by shoaib30** [Saluki/nestjs-template#23]
The restricted guard requires a JWT to access. The docs do not cover how to create a JWT or a sample JWT that can be used. I understand generating and using JWT is outside the scope of this template, but it would be helpful to point users in the right direction especially in terms of what claims are required.

Would it make sense to have a sample JWT like :
`eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJERUZBVUxUX0lTU1VFUiIsImlhdCI6MTYzMTEwNDMzNCwicm9sZSI6InJlc3RyaWN0ZWQifQ.o2HcQBBpx-EJMcUFiqmAiD_jZ5J92gRDOyhybT9FakE`

that can be added to the docs for getting started and testing the protected routes.

I can create a PR with the  chages

**Comment by Saluki** [comment]
As seen in PR #22 this is indeed a nice improvement to the project. Thanks !
