### ISSUE TITLE
Hi,How do you create Passengermodule?

### ISSUE THREAD

**Issue by NG-GGBond** [Saluki/nestjs-template#8]
```
nest g m passenger
create folder controller
nest g co passenger 
move passengerController ...
```
Or "One Command"

**Comment by Saluki** [comment]
Hi @NG-GGBond 

This NestJS template was conceived with a very specific structure that has worked well over time for some projects. The file structure is thus opiniated and was created before the Nest CLI introduced all schematic generation.

I would advise you to clone the repository and change the PassengerModule to your needs. Should you need another module _(NotificationModule for example)_ in your application, simply create a new directory structure based on _PassengerModule_ for the new module.

**Comment by NG-GGBond** [comment]
@Saluki 
Thank you for your reply.   : )
